name: Node.js CI/CD with S3 and CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: AWS 자격 증명 설정
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm test

      - name: Upload to S3
        run: |
          zip -r app.zip ./build
          aws s3 cp app.zip s3://kimlrlr-bucket/releases/app.zip

      - name: Deploy to EC2 via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name 'kimlrlr-codedeploy' \
            --deployment-group-name 'dev' \
            --s3-location bucket=kimlrlr-bucket,key=releases/app.zip,bundleType=zip
