name: Node.js CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - run: npm run build --if-present
      - run: npm run lint
      - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Test SSH Connection1
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     SERVER_IP: ${{ secrets.SERVER_IP }}
      #     SERVER_USER: ${{ secrets.SERVER_USER }}
      #   run: |
      #     echo "$SSH_PRIVATE_KEY" > key
      #     chmod 600 key
      #     ssh -i key -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "echo SSH connection successful"
      #     rm key

      - name: ssh pipelines
        uses: cross-the-world/ssh-pipeline@master
        env:
          WELCOME: 'ssh pipeline'
        with:
          host: ${{ secrets.SSH_PRIVATE_KEY }}
          user: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.PORT }}
          connect_timeout: 10s
          script: |
            (rm -rf /home/github/test || true)
            ls -la  
            echo $WELCOME 
            mkdir -p /home/github/test/test1 && 
            mkdir -p /home/github/test/test2 &&

      # - name: Setup SSH
      #   uses: webfactory/ssh-agent@v0.9.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Deploy to server
      #   run: |
      #     ssh -o StrictHostKeyChecking=no kimlrlr@127.0.0.1 'cd /home/kimlrlr/node-ci-cd-test && git pull origin main && ./deploy_script.sh'
