name: Node.js CI/CD with S3와 CodeDeploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Node.js 설정 및 의존성 설치
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present

      - name: lint 및 테스트
        run: |
          npm run lint
          npm test

      - name: AWS 자격 증명 설정
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: S3에 업로드
        run: |
          zip -r app.zip .
          aws s3 cp app.zip s3://kimlrlr-bucket/releases/app.zip

      - name: CodeDeploy를 통해 EC2로 배포
        run: |
          aws deploy create-deployment \
          --application-name 'kimlrlr-codedeploy' \
          --deployment-group-name 'dev' \
          --s3-location bucket=kimlrlr-bucket,key=releases/app.zip,bundleType=zip
