name: Node.js CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - run: npm run build --if-present
      - run: npm run lint
      - run: npm test

  # deploy:
  #   runs-on: self-hosted
  #   needs: build

  #   steps:
  #     # - name: Setup SSH for GitHub access
  #     #   run: |
  #     #     mkdir -p ~/.ssh
  #     #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
  #     #     chmod 600 ~/.ssh/id_rsa
  #     #     ssh-keyscan -H github.com >> ~/.ssh/known_hosts

  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Run commands on self-hosted runner
  #       run: |
  #         cd /home/kimlrlr/node-ci-cd-test && git pull origin main && npm install
